name: Build Android APK and AAB

on:
  workflow_dispatch:
  push:
    branches: [ "main", "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'

      # استفاده از اکشن رسمی گریدل برای کش کردن و سرعت بالاتر
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3

      # دادن دسترسی اجرا به فایل gradlew (بسیار مهم)
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build debug APK
        run: ./gradlew assembleDebug --stacktrace

      - name: Build release AAB
        run: ./gradlew bundleRelease --stacktrace

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: amar-dukht-debug-apk
          # مسیر پیش‌فرض خروجی APK در اندروید استودیو
          path: app/build/outputs/apk/debug/app-debug.apk

      - name: Upload AAB
        uses: actions/upload-artifact@v4
        with:
          name: amar-dukht-release-aab
          # مسیر پیش‌فرض خروجی AAB در اندروید استودیو
          path: app/build/outputs/bundle/release/app-release.aab
